### ISSUE TITLE
[Staging] Translation - Site goes to grey in various cases

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1577]
## Issue
*Site goes to grey in different scenarios.*

## URL
*https://dsgoproxyapp.azurewebsites.net/account#account-information*

## Steps to reproduce
*Chrome:
Select a region from the drop-down. Repeat the region selection a few times. It might go to grey after 2nd, 3rd try.

Firefox, Edge:
Go to Account information. Site goes to grey.

Error from console:
Uncaught TypeError: t.find is not a function
    We get-country-meta.js:3
    value account.js:290
    value account.js:287
    value account.js:258
    React 12
    unstable_runWithPriority scheduler.development.js:653
    React 6
    Redux 12
    nn network.js:243
get-country-meta.js:3:27
    We get-country-meta.js:3
    value account.js:290
    forEach self-hosted:216
    value account.js:287
    value account.js:258
    React 11
    Th self-hosted:1218
    zu React
    unstable_runWithPriority scheduler.development.js:653
    React 6
    onStateChange Redux
    <anonymous> self-hosted:1171
    Redux 2
    <anonymous> self-hosted:1171
    onStateChange Redux
    <anonymous> self-hosted:1171
    Redux 2
    <anonymous> self-hosted:1171
    onStateChange Redux
    <anonymous> self-hosted:1171
    Redux 3
    <anonymous> self-hosted:1171
    Redux 2
    nn network.js:243
The above error occurred in the <a> component:
    in a (created by Connect(a))
    in Connect(a) (created by t)
    in t (created by a)
    in a (created by Connect(a))
    in Connect(a)
    in t
    in t
    in t (created by t)
    in t
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by eh)
    in a (created by eh)
    in eh

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

*

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
**

## Related feature
**

## Criticality/Urgency
*Critical*

**Comment by batpad** [comment]
@tovari I'm unable to reproduce this.

Perhaps this is some-how specific to the user you're logged in as / some combination of things? If you could share the credentials for the user you're logging in as on staging as a private message on Teams, perhaps this helps me reproduce this issue.

**Comment by batpad** [comment]
@tovari this should now be fixed on staging. Could you verify, also please update in case you are facing a grey screen anywhere? Thank you again for this catch.

**Comment by guipizzini** [comment]
@tovari please can you check and test? it works fine for me and seems to be fixed

**Comment by tovari** [comment]
@batpad, @frozenhelium, @guipizzini, I still have the issue.
I have created the following FR on the spanish UI using the tovari-test-spanish account. I cannot open the FR though as the site goes to grey again:
https://dsgoproxyapp.azurewebsites.net/emergencies/4089#details

**Comment by frozenhelium** [comment]
@batpad @GregoryHorvath These issue are being caused because we have not set English as fallback language. Hence empty strings of undefined / null is being received to the fields. Once we set English as fallback language it should be fixed.
CC: @thenav56

**Comment by tovari** [comment]
It works now for me as well :)
