### ISSUE TITLE
Situation Reports available only if you're logged in

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#203]
Situation Reports for all operations should be publicly available - meaning even if you're not logged in.

cc @guipizzini

**Comment by dereklieu** [comment]
I believe this is fixed @k-som can you check and close if it is?

**Comment by k-som** [comment]
Just checked it, it's still the same:
![sitrep](https://user-images.githubusercontent.com/25579864/37146487-2dd9f488-22c4-11e8-8a8f-723992571e34.jpg)
