### ISSUE TITLE
login / sign up issues

### ISSUE THREAD

**Issue by danbjoseph** [IFRCGo/go-frontend#212]
Trying to register, I get an error that the user already exists:
<img width="525" alt="screen shot 2018-03-14 at 7 57 39 am" src="https://user-images.githubusercontent.com/4806884/37401131-7efc878e-275d-11e8-8475-c93975b4e2e9.png">

Trying to get a reminder of my password I also get an error:
<img width="1112" alt="screen shot 2018-03-14 at 7 56 47 am" src="https://user-images.githubusercontent.com/4806884/37401161-941eb0ba-275d-11e8-9660-d8cc60384762.png">

**Comment by dereklieu** [comment]
@danbjoseph the first part is working as expected, and I believe the password recovery is failing because there are two records with that email address in the user table. One was created on 2/22, the other on 3/7. Is it possible that a second account was created in the admin? If so, that could have bypassed the unique email validation. 

If you allow me to delete one of the accounts, or simply change it to a different email address, we could verify if this indeed is the issue.

**Comment by danbjoseph** [comment]
change one to dan.b.joseph@gmail.com?

**Comment by dereklieu** [comment]
Done, please try the password recovery workflow now.

**Comment by danbjoseph** [comment]
got the email, reset my password, but still can't login
is username = email?

**Comment by dereklieu** [comment]
No, there is a separate username and that is what the login field uses right now. I would like to allow either username or login in that field, but we didn't get to it in phase 1.

**Comment by dereklieu** [comment]
No further actions.
