### ISSUE TITLE
Response Documents filtering

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#396]
## Issue

Filtering of documents not working on the "Response Documents" on the Emergency Pages despite having them created in the django framework. This requires a fix urgently please.

<img width="688" alt="screen shot 2018-08-06 at 14 11 06" src="https://user-images.githubusercontent.com/23258092/43711127-ce16e6c4-9982-11e8-927c-3a0231657b44.png">

**Comment by dereklieu** [comment]
@guipizzini you have to create the types, then assign them to each document. Documents don't have types by default.

Create types:
https://prddsgocdnapi.azureedge.net/admin/api/situationreporttype/

Add types to documents:
https://prddsgocdnapi.azureedge.net/admin/api/situationreport/

**Comment by guipizzini** [comment]
Derek, we did create types and did assign them. Still not working.

**Comment by dereklieu** [comment]
Can you please send a link to an emergency page where this isn't working?

I assigned the infographic report on [this emergency page](https://go.ifrc.org/emergencies/3124) a type, and filtering is working for it.

![filter](https://user-images.githubusercontent.com/1590802/43717784-9a064766-9956-11e8-97b0-40403f37bcc7.gif)

**Comment by guipizzini** [comment]
Here are two different emergencies, with one related to the same you have - but it is not working for us (different browsers, different users)...

<img width="1244" alt="screen shot 2018-08-06 at 17 03 03" src="https://user-images.githubusercontent.com/23258092/43718146-d1bb53ce-999a-11e8-8de3-a06d82215fdf.png">
<img width="1244" alt="screen shot 2018-08-06 at 17 03 39" src="https://user-images.githubusercontent.com/23258092/43718147-d1e8417c-999a-11e8-8ffe-e7fcc8639199.png">

**Comment by guipizzini** [comment]
![screencapture-go-ifrc-org-emergencies-3067-2018-08-07-09_33_36](https://user-images.githubusercontent.com/23258092/43761296-fd29045e-9a24-11e8-956c-2249f95654da.png)

@dereklieu now the section totally disappeared, whether I log in or not...

**Comment by dereklieu** [comment]
Should be fixed by https://github.com/IFRCGo/go-frontend/pull/421, waiting to confirm.

**Comment by guipizzini** [comment]
Fixed and working. Thanks

**Comment by guipizzini** [comment]
Sorry @dereklieu had to re-open as it is still not working. In addition, the documents will be displayed only when they are set as "public" and not displayed (Despite being logged in) when marked as "ifrc" or "membership"

**Comment by dereklieu** [comment]
Thanks @guipizzini for checking, the non-public items are now working as well.
