### ISSUE TITLE
Implement Breadcrumbs

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#770]
Implement navigation breadcrumbs as per the design.

Example Breadcrumbs in design: https://projects.invisionapp.com/share/P9SA110GT4S#/screens/356658484 - we need a "breadcrumb" at the top of the page for a country page, for eg like `Home > Asia Pacific > Philipines`. Similarly, for other pages, indicating where the user is, as per the design.

One thing to note, the breadcrumbs for a page will always be the same, regardless of how the user navigated to that page. So, for eg. the country page will always have `Home > <Region> > <Country>` as the breadcrumb, no matter how the user actually navigated to the country page. This is as per design, and makes it more straightforward to implement, staying away from strange edge cases.

For implementation, I will:

 - Create a `<Breadcrumb>` component that accepts a `crumbs` parameter or so which is an array of objects each having a `title` and `link`. The breadcrumb component will then render the breadcrumb.
 - For all views that require breadcrumbs, add a `getCrumbs()` helper or so to get the page hierarchy, and call the breadcrumb component at the appropriate place on the page.

Will post here if the `getCrumbs()` for any of the particular views turns out to be complex for some reason, but I think if we don't have the crumbs be dependent on the order of the user's navigation, this can be fairly straightforward to implement.

**Comment by batpad** [comment]
Updated this ticket to add some details, link to the design, and make some implementation notes. cc @nanometrenat @necoline

**Comment by LukeCaley** [comment]
Results of QA to be posted here by @batpad / Dev Seed team.

**Comment by karitotp** [comment]
I am reviewing here https://dsgoproxyapp.azurewebsites.net/ and I do not find any breadcrumbs. 

When I reviewed this before in https://ifrc-go-feature-react-bread-crumb.surge.sh/ I found most of the breadcrumbs like region and country. The breadcrumbs which I could not find were:
 - Field Report: home > reports(account/notifications) > field report
 - PER Forms: home > account > PER form
 - Tables(view all ...): home > name of table

ref: https://github.com/IFRCGo/go-frontend/pull/1026#issuecomment-610407704

**Comment by guipizzini** [comment]
So the breadcrumbs work smoothly for all the pages except:

- Tabs on the specific pages
- On the login page
- On the register page

@lauripynnonen anything else I missed?

**Comment by lauripynnonen** [comment]
If you look at a PER form there's no breadcrumb
Home - Account - PER form tab - click an active form
![image](https://user-images.githubusercontent.com/8285694/80213135-04340f80-8639-11ea-962f-71af9d9a1098.png)

**Comment by lauripynnonen** [comment]
Otherwise works as intended
@nanometrenat not sure if this is a bug, but you created an emergency to Puerto Rico, but Go doesn't have the country Puerto Rico, so clicking that country seems to take the user to an empty page
![image](https://user-images.githubusercontent.com/8285694/80213448-79074980-8639-11ea-80ed-d96caa0e06e6.png)

**Comment by nanometrenat** [comment]
@lauripynnonen what does your comment above have to do with breadcrumbs?! ;)  re Puerto Rico yes this is a known data issue awaiting some love when the GIS person is appointed: https://github.com/IFRCGo/go-frontend/issues/938

**Comment by nanometrenat** [comment]
Hi team, I hate to raise this againagain but the original reason why ticket #928 was logged (which is why this breadcrumbs ticket got prioritised) is because when I am on an Emergency page there is no link to the Country that it belongs to.  The breadcrumbs were going to be implemented according to the logic in this comment: https://github.com/IFRCGo/go-frontend/issues/928#issuecomment-605993087
whereby for an emergency page the breadcrumbs would show `home > emergencies > region > country > emergency`
However when I go to `https://ifrc-go-feature-react-bread-crumb.surge.sh/emergencies/3833#details` the breadcrumbs show `Home > Emergencies > Natalie test one - Americas 01/20` which doesn't tell me which country it is linked to.

On an Emergency page there is no point having breadcrumbs that show you exactly what is shown in the top menu of big buttons - I already know I'm in the Emergencies section.  Please make sure the breadcrumbs allow you to see where the page fits in the bigger picture.

@LukeCaley are you able to please finalise this one for once and for all?  (PS inability to navigate from an Emergency page to the associated Country page took me lots of extra time last night flicking between back end and front end - but other users can't do this to identify).  We are promoting Emergency page links in things like Ops Updates but unless the Emergency pages show the countries then we have issues.

**Comment by LukeCaley** [comment]
@batpad to confirm implementation plan as per https://github.com/IFRCGo/go-frontend/issues/928#issuecomment-605993087, hoping that this could be included in mini-release 27/04.  Currently this does not pass UAT.

**Comment by LukeCaley** [comment]
@batpad please confirm if you have all the business requirement logic required to proceed with this build

**Comment by LukeCaley** [comment]
Xref https://github.com/IFRCGo/go-frontend/issues/1122

**Comment by batpad** [comment]
This is ready for testing at https://kamicut-ifrc-go-feature-react-bread-crumb.surge.sh/ and should address #1322 as well. cc @nanometrenat @karitotp

**Comment by batpad** [comment]
@karitotp thank you!

The breadcrumbs on the emergency page are indeed slightly weird, and the ordering of the Country Name and `Emergencies` seems wrong "sometimes". Also, in the Breadcrumb it says "Emergency", where it maybe preferrable to have the actual title of the emergency?

Based on my understanding, the correct breadcrumb on an individual emergency page, should always be:

Home -> Emergencies -> `Country Name` -> `Emergency Title`

eg.

Home -> Emergencies -> India -> Tropical Cyclone in Goa

And there Home should link to Home, Emergencies to All Emergencies, India to the India country page.

@kamicut let me know if this makes sense and if this is something you're able to look at. We can likely reach out to @necoline for help if needed :-)

Also, we need to add the breadcrumb on the about page - I can go ahead and do that and push to the existing branch.

**Comment by batpad** [comment]
Moving this ticket back to `In Progress` while we resolve the issues identified.

**Comment by batpad** [comment]
It is completely confounding why this particular Emergency seems to have the order on the breadcrumbs wrong: http://localhost:3000/emergencies/3675#details

For other emergencies I checked, the order seems correct - i.e. Home -> Emergencies -> Country -> Emergency

For just this one, the ordering is Home -> Country -> Emergencies -> Emergency

**Comment by batpad** [comment]
So, the problem seems to be that `react-breadcrumbs-dynamic` defaults to ordering the breadcrumbs by the length of the URL: https://www.npmjs.com/package/react-breadcrumbs-dynamic

We need to specify our own compare function to have it guaranteed to order based on the order in of the `crumbs` array.

**Comment by batpad** [comment]
@karitotp I have updated the code and uploaded to a new surge URL (sorry for the confusion on the URLs). The latest code can be tested here: https://batpad-ifrc-go-test-breadcrumbs.surge.sh

I am pretty sure I have fixed the inconsistent ordering of the breadcrumbs on the country pages. And have also added the breadcrumb on the Resources page. Would be great to test.

@karitotp  - can you also test navigating to the country page from different places? I thought I saw a crash when navigating to the country page in some scenario, but was unable to reproduce - if you could just try going to the country page from different places on the site and seeing if anything causes the page to crash, would be great.

**Comment by nanometrenat** [comment]
Yep https://batpad-ifrc-go-test-breadcrumbs.surge.sh/countries/282#operations is still crashing - potentially because it's for a country record of type region rather than type country (https://github.com/IFRCGo/go-api/issues/759)

However as it can be navigated-to via the search then we should definitely fix the crash!  And separately address the question of whether these country pages should exist as part of the geospatial bigger picture thing.

**Comment by karitotp** [comment]
@batpad, I reviewed the breadcrumbs for an emergency page and  currently it is displayed as Emergency > Country > Emergencies > Home --> https://batpad-ifrc-go-test-breadcrumbs.surge.sh/emergencies/4026#details

- The order of the country in the breadcrumbs of a emergency, is same for all emergencies page, but it is shown in the reverse order to the one you mentioned in the above comment: `Home -> Emergencies -> Country -> Emergency`

-  Also instead the name of the emergency, it is still displaying as  "Emergency"

The inverted order in the breadcrumbs is for all the pages. Is this an expected behavior? Some examples are:
- Resources: Resources > Home
- Deployments: Deployments > Home
- Country: Pakistan > Asia Pacific > Home
- Account: Account > Home

Regarding the block when we sailed to some countries, I did not find another country with this problem, but what Natalie shared above is crashing for me too.

**Comment by mariam-yu** [comment]
@nanometrenat @batpad @karitotp Not sure who is working on this, but here are some thoughts:

**UX**: the order is reversed, but I'm sure you've seen that already; Also, it should have the actual emergency name.

**UI**: The breadcrumbs should be left aligned with the nav and have a bigger padding on top (example: https://projects.invisionapp.com/share/8FXCLVKEY6C#/screens/421178284_4-3-1_GO_Specific-Emergency_Test1). The actual font size, color details are on Zeplin.

Please let me know if any questions.

**Comment by batpad** [comment]
> UX: the order is reversed, but I'm sure you've seen that already; Also, it should have the actual emergency name.

Will revert to using the actual emergency name :+1: 

The order being reversed is strange, looking into it - it's correct on Firefox and wrong on Chrome :-(

> UI: The breadcrumbs should be left aligned with the nav and have a bigger padding on top (example: https://projects.invisionapp.com/share/8FXCLVKEY6C#/screens/421178284_4-3-1_GO_Specific-Emergency_Test1). The actual font size, color details are on Zeplin.

@imohkay can I ask for your help here in styling the breadcrumb element in the `feature/react-bread-crumb` branch to match the spec in Zeplin?

**Comment by batpad** [comment]
Have updated https://batpad-ifrc-go-test-breadcrumbs.surge.sh with these fixes:

> The order of the country in the breadcrumbs of a emergency, is same for all emergencies page, but it is shown in the reverse order to the one you mentioned in the above comment: Home -> Emergencies -> Country -> Emergency

Fixed.

> Also instead the name of the emergency, it is still displaying as "Emergency"

Fixed.

> https://kamicut-ifrc-go-feature-react-bread-crumb.surge.sh/countries/282#operations does not load (grey screen) but loads fine in Staging.

This should be fixed - in case a country is not part of a region, it will not show the region part of the breadcrumb.

cc @karitotp @nanometrenat

**Comment by karitotp** [comment]
Tested and all is working good to me!

**Comment by nanometrenat** [comment]
Hi @batpad @karitotp 

> * Spelling mistake on Field Reports page (Home > Emgergencies > Report) https://kamicut-ifrc-go-feature-react-bread-crumb.surge.sh/reports/9618 also I'm not sure whether it is intended that the breadcrumbs say the generic "Home > Emergencies > Report" or whether it's intended to say the specific names e.g. "Home > Grenada: COVID-19" etc.  Anyway will leave it to others to confirm intent here.

When in Field Reports, the spelling mistake mentioned above is still there ("Emgergencies") .

Also @mariam-yu can you please confirm that it's intended to just say Home > Emergencies > Report for Field Reports, or whether you're wanting Country/ Emergency / Field Report _names_ in the breadcrumbs?  In the case of FRs the emergency and country links are already in the lozenges so it's not such a big deal either way like it is for emergencies.  Cheers

**Comment by mariam-yu** [comment]
@nanometrenat I think it should specify the names. Thanks!

**Comment by batpad** [comment]
> When in Field Reports, the spelling mistake mentioned above is still there ("Emgergencies") .

Thanks for the catch! Fixed the typo as well as using Field Report names now instead of just saying "Report" in the breadcrumb.

**Comment by imohkay** [comment]
@mariam-yu You can take a look at the breadcrumbs with styles matching Zeplin here: https://batpad-ifrc-go-test-breadcrumbs.surge.sh/

**Comment by mariam-yu** [comment]
@karitotp @nanometrenat 

I reviewed most of the paths for breadcrumbs, and overall looks good. There are a couple of things though:
- On the Account page, when navigating to a specific PER form, it says Afghanistan. It should stay as Account. Also, better to put the name of the specific form you are clicking into.
<img width="1026" alt="Screen Shot 2020-06-18 at 3 04 39 PM" src="https://user-images.githubusercontent.com/60006476/85031095-8c88e980-b17e-11ea-88b6-cd2ca271edc7.png">
- For the extra table views (All Operations, All Emergencies, etc.) - better to match the title or at least put All.
<img width="1385" alt="Screen Shot 2020-06-18 at 4 09 10 PM" src="https://user-images.githubusercontent.com/60006476/85031269-bf32e200-b17e-11ea-8f49-06b5ff5fb91e.png">
Also, in other screens it still shows the same path: home > Operations, even though you are, say in Fiji page. It should say: Home > Region > Country > All ...
<img width="1218" alt="Screen Shot 2020-06-18 at 4 09 06 PM" src="https://user-images.githubusercontent.com/60006476/85031404-ebe6f980-b17e-11ea-9ef7-22b6c3c22a1a.png">
- Lastly, it may be a bit strange to have the field reports be connected to emergencies page (as they are tied to specific emergencies. But I propose to wait on this and keep as is, as the new structure in the wires may solve that later on.
<img width="1205" alt="Screen Shot 2020-06-18 at 4 10 58 PM" src="https://user-images.githubusercontent.com/60006476/85031735-51d38100-b17f-11ea-8ae5-888a39031520.png">

**Comment by nanometrenat** [comment]
> * On the Account page, when navigating to a specific PER form, it says Afghanistan. It should stay as Account. Also, better to put the name of the specific form you are clicking into.
@mariam-yu I'm confused - if you remove the name of the country that that specific PER form relates to, how will you be able to tell the difference between different countries' forms?

**Comment by nanometrenat** [comment]
> * On the Account page, when navigating to a specific PER form, it says Afghanistan. It should stay as Account. Also, better to put the name of the specific form you are clicking into.

@mariam-yu I'm confused - if you remove the name of the country that that specific PER form relates to, how can the user tell the difference between different countries' forms, and which one they're in (if it's not the overview form, which has the country name)?  @teklal what are your thoughts on the PER form breadcrumbs?

**Comment by mariam-yu** [comment]
@nanometrenat That's good point, but I don't think the way it is makes sense, since you lose the thread and somehow are linked back to a country page that may not be relevant in the context. I'd propose the country dropdown to be a part of the page, above the form or part of the form. I doubt that we need the breadcrumbs to reflect that. But if we do, may be we can put the country name - form. Please let me know if this makes sense.

**Comment by batpad** [comment]
> On the Account page, when navigating to a specific PER form, it says Afghanistan. It should stay as Account. Also, better to put the name of the specific form you are clicking into.

Done.

>  For the extra table views (All Operations, All Emergencies, etc.) - better to match the title or at least put "All...". Also, on other screens it still shows the same path: Home > Operations, even though you are, say, on the Fiji page. It should say: Home > Region > Country > All ... 

Done.

I'm going to go ahead and merge this to staging for final testing.

**Comment by batpad** [comment]
This is now on staging. @karitotp will be great to do a comprehensive final test of breadcrumbs, especially related to the changes mentioned in the last few comments. Thank you!

**Comment by karitotp** [comment]
> On the Account page, when navigating to a specific PER form, it says Afghanistan. It should stay as Account. Also, better to put the name of the specific form you are clicking into.

Now it is displayed as Account instead the country, but about the name of the form it is still displayed just as "PER Form": Home > Account > PER Form

> For the extra table views (All Operations, All Emergencies, etc.) - better to match the title or at least put "All...". Also, on other screens it still shows the same path: Home > Operations, even though you are, say, on the Fiji page. It should say: Home > Region > Country > All ...

- The title for all operations, all emergency, all reports... it is now displayed just as: Home > 
- For all operations in a country it is displayed E.g. as: Home > Fiji > Operations

**Comment by batpad** [comment]
> Now it is displayed as Account instead the country, but about the name of the form it is still displayed just as "PER Form": Home > Account > PER Form

@karitotp I am unable to reproduce this - it says for eg. `Home > Account > PER: Operational Capacity 2` on https://dsgoproxyapp.azurewebsites.net/per-forms/operational-capacity-2/14 . Could you confirm on what URL you still see `PER Form` appear in the Breadcrumb?

**Comment by karitotp** [comment]
@batpad 

The name is shown here https://dsgoproxyapp.azurewebsites.net/per-forms/operational-capacity-2/14.
What I reviewed was this https://dsgoproxyapp.azurewebsites.net/view-per-forms/a5/80, here the name is not shown.

**Comment by karitotp** [comment]
:+1: @batpad, now the name is also displayed here https://dsgoproxyapp.azurewebsites.net/view-per-forms/a5/80

**Comment by LukeCaley** [comment]
Closing as this works in PROD. Any small errors should be picked up in new tickets.
